// src/components/MentionDropdown.vue
<template>
  <teleport to="body">
    <div
      v-if="shown && (filteredUsers.length > 0 || hasAll)"
      class="mention-dropdown"
      :style="{
        position: 'fixed',
        top: dropdownPosition.top + 'px',
        left: dropdownPosition.left + 'px',
        zIndex: 99999,
      }"
    >
      <div class="mention-item mention-all" @click="selectMention('all')">
        <span class="mention-avatar">👥</span>
        <span class="mention-text">@all</span>
      </div>

      <div v-if="filteredUsers.length > 0 && hasAll" class="mention-divider"></div>

      <div
        v-for="user in filteredUsers"
        :key="user.id"
        class="mention-item"
        @click="selectMention(user.username)"
      >
        <span class="mention-avatar">{{ user.animal }}</span>
        <span class="mention-text">@{{ user.username }}</span>
      </div>
    </div>
  </teleport>
</template>

<script setup lang="ts">
import { computed, ref, watch, nextTick } from 'vue'
import type { User } from '@/types'
import { getLastMentionBeingTyped } from '@/utils/mentionFormatter'

interface Props {
  text: string
  cursorPosition: number
  users: User[]
  currentUserId?: string
}

interface Emits {
  (e: 'select', username: string): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const shown = ref(false)
const dropdownPosition = ref({ top: 0, left: 0 })

const mentionData = computed(() => {
  return getLastMentionBeingTyped(props.text, props.cursorPosition)
})

const shouldShow = computed(() => {
  return mentionData.value !== null
})

watch(shouldShow, async (val) => {
  shown.value = val
  if (val) {
    await nextTick()
    positionDropdown()
  }
})

watch(() => props.text, () => {
  if (shown.value) {
    positionDropdown()
  }
})

const hasAll = computed(() => {
  if (!mentionData.value) return false
  return 'all'.startsWith(mentionData.value.mention.toLowerCase())
})

const filteredUsers = computed(() => {
  if (!mentionData.value) return []

  const query = mentionData.value.mention.toLowerCase()
  return props.users
    .filter(
      (user) =>
        user.id !== props.currentUserId &&
        user.username.toLowerCase().startsWith(query),
    )
    .slice(0, 5)
})

function positionDropdown() {
  const textarea = document.querySelector('textarea') as HTMLTextAreaElement
  if (!textarea) return

  const rect = textarea.getBoundingClientRect()
  const scrollTop = window.scrollY
  
  // Calculate actual dropdown height based on filtered items
  const itemCount = filteredUsers.value.length + (hasAll.value ? 1 : 0)
  const itemHeight = itemCount * 48 // 48px per item
  const containerPadding = 16 // 8px top + 8px bottom
  const dividerHeight = filteredUsers.value.length > 0 && hasAll.value ? 1 : 0
  const totalHeight = itemHeight + containerPadding + dividerHeight
  
  // Position dropdown above textarea with consistent bottom position
  // Add 20px gap to avoid covering textarea
  const topPosition = rect.top + scrollTop - totalHeight - 20
  
  dropdownPosition.value = {
    top: topPosition,
    left: rect.left + window.scrollX,
  }
}

// Reposition dropdown when filtered items change
watch([filteredUsers, hasAll], () => {
  if (shown.value) {
    positionDropdown()
  }
})

function selectMention(username: string) {
  emit('select', username)
  shown.value = false
}
</script>

<style scoped>
.mention-dropdown {
  background: white;
  border-radius: 12px;
  box-shadow: 0 5px 25px rgba(0, 0, 0, 0.15);
  width: 240px;
  max-height: 300px;
  overflow-y: auto;
  padding: 8px 0;
  position: relative;
  z-index: 99999;
}

.mention-item {
  display: flex;
  align-items: center;
  padding: 12px 16px;
  cursor: pointer;
  transition: background-color 0.2s ease;
  user-select: none;
}

.mention-item:hover {
  background-color: #1976d2;
}

.mention-item:hover .mention-avatar,
.mention-item:hover .mention-text {
  color: white;
}

.mention-avatar {
  font-size: 1.3em;
  margin-right: 12px;
  min-width: 28px;
  text-align: center;
  transition: color 0.2s ease;
}

.mention-text {
  color: #111;
  font-weight: 500;
  font-size: 0.95rem;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  transition: color 0.2s ease;
}

.mention-divider {
  height: 1px;
  background: #e0e0e0;
  margin: 4px 0;
}

.mention-all {
  margin-bottom: 4px;
}

.mention-all:hover {
  background-color: #ff9800;
}
</style>

// src/components/MentionDropdown.tsx
import React, { useState, useEffect, useMemo } from 'react'
import ReactDOM from 'react-dom'
import type { User } from '@/types'
import { getLastMentionBeingTyped } from '@/utils/mentionFormatter'

interface MentionDropdownProps {
  text: string
  cursorPosition: number
  users: User[]
  currentUserId?: string
  onSelect: (username: string) => void
}

export const MentionDropdown: React.FC<MentionDropdownProps> = ({
  text,
  cursorPosition,
  users,
  currentUserId,
  onSelect,
}) => {
  const [dropdownPosition, setDropdownPosition] = useState({ top: 0, left: 0 })

  const mentionData = useMemo(() => {
    return getLastMentionBeingTyped(text, cursorPosition)
  }, [text, cursorPosition])

  const shouldShow = mentionData !== null

  const hasAll = useMemo(() => {
    if (!mentionData) return false
    return 'all'.startsWith(mentionData.mention.toLowerCase())
  }, [mentionData])

  const filteredUsers = useMemo(() => {
    if (!mentionData) return []
    const query = mentionData.mention.toLowerCase()
    return users
      .filter(
        (user) =>
          user.id !== currentUserId &&
          user.username.toLowerCase().startsWith(query)
      )
      .slice(0, 5)
  }, [mentionData, users, currentUserId])

  const positionDropdown = () => {
    const textarea = document.querySelector('textarea') as HTMLTextAreaElement
    if (!textarea) return

    const rect = textarea.getBoundingClientRect()
    const scrollTop = window.scrollY
    
    const itemCount = filteredUsers.length + (hasAll ? 1 : 0)
    const itemHeight = itemCount * 48
    const containerPadding = 16
    const dividerHeight = filteredUsers.length > 0 && hasAll ? 1 : 0
    const totalHeight = itemHeight + containerPadding + dividerHeight
    
    const topPosition = rect.top + scrollTop - totalHeight - 20
    
    setDropdownPosition({
      top: topPosition,
      left: rect.left + window.scrollX,
    })
  }

  useEffect(() => {
    if (shouldShow) {
      positionDropdown()
    }
  }, [shouldShow, text, filteredUsers, hasAll])

  if (!shouldShow || (filteredUsers.length === 0 && !hasAll)) {
    return null
  }

  return ReactDOM.createPortal(
    <div
      className="mention-dropdown"
      style={{
        position: 'fixed',
        top: dropdownPosition.top + 'px',
        left: dropdownPosition.left + 'px',
        zIndex: 99999,
      }}
    >
      {hasAll && (
        <div className="mention-item mention-all" onClick={() => onSelect('all')}>
          <span className="mention-avatar">👥</span>
          <span className="mention-text">@all</span>
        </div>
      )}

      {filteredUsers.length > 0 && hasAll && <div className="mention-divider"></div>}

      {filteredUsers.map((user) => (
        <div
          key={user.id}
          className="mention-item"
          onClick={() => onSelect(user.username)}
        >
          <span className="mention-avatar">{user.animal}</span>
          <span className="mention-text">@{user.username}</span>
        </div>
      ))}
    </div>,
    document.body
  )
}

export default MentionDropdown
